name: Weekly Wayback Scraper

on:
  schedule:
    - cron: '40 15 * * 6'  # Runs every Saturday at 20:27 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Use a stable Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas beautifulsoup4 waybackpy==3.0.6  # Specify compatible version

      - name: Run the script
        run: |
          mkdir -p wayback_results  
          python wayback.py

      - name: Commit and push results
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          if [[ -n "$(git status --porcelain)" ]]; then
            git add wayback_results/*
            git commit -m 'Update Wayback Machine data'
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
